# Local/Dev
db:
    image: postgres
    restart: always
    env_file:
        - docker-compose-config/db.env

web:
    build: ./app
    volumes:
        - ./app:/app
    ports:
        - "8080:8080"
    links:
        - db
    environment:
        RUN_TYPE: runserver
    env_file:
        - docker-compose-config/web.env
